GostosinhoEmpregos/Models/ErrorViewModel.cs
using System;

namespace GostosinhoEmpregos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GostosinhoEmpregos/Models/VagaViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GostosinhoEmpregos.Models
{
    public class VagaViewModel
    {
        public int Id { get; set; }
        public DateTime DataCadastro { get; set; }
        [Display(Name ="Funcao")]
        [Required(ErrorMessage = "Por favor insira a funcao")]
        [StringLength(100,ErrorMessage ="Erro na quantidade de caracteres!",  MinimumLength = 3)]
        public string Funcao { get; set; }

        [Display(Name = "Descrição")]
        [StringLength(3000, ErrorMessage = "Erro na quantidade de caracteres!", MinimumLength = 50)]
        public string Descricao { get; set; }

        [Display(Name = "Data de validade")]
        public DateTime DataValidade { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Cidade é obrigatorio")]
        [Display(Name = "Cidade")]
        public string Cidade { get; set; }

        [Required (ErrorMessage = "CPF obrigatório", AllowEmptyStrings = false)]
        [Display(Name = "Cpf")]
        [DisplayFormat(DataFormatString = "{0:000.000.000-00}", ApplyFormatInEditMode = true)]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Cpf incorreto")]
        public string Cpf { get; set; }

        [Required(ErrorMessage = "O nome do responsavel pela vaga é obrigatorio", AllowEmptyStrings = false)]
        [Display(Name = "Nome Completo do responsavel")]
        [StringLength(100,ErrorMessage = "Erro ao preencher o nome"  ,MinimumLength = 5)]
        public string NomeResponsavel { get; set; }
    }
}

GostosinhoEmpregos/Controllers/HomeController.cs
using GostosinhoEmpregos.BLL.BLL.master;
using GostosinhoEmpregos.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GostosinhoEmpregos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        //GET /home
        public IActionResult Index()
        {
            ViewBag.ListaDeVagas = Vaga.RecuperarVagasNovas();

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GostosinhoEmpregos/Controllers/VagaController.cs
using GostosinhoEmpregos.BLL.BLL.master;
using GostosinhoEmpregos.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace GostosinhoEmpregos.Controllers
{
    [Controller]
    public class VagaController : Controller
    {
        //GET /Vaga/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        //GET /Vaga/VerVaga
        public IActionResult VerVaga(int idVaga)
        {
            ViewBag.Vaga = Vaga.RecuperarVagaPorId(idVaga);
            return View();
        }

        [HttpPost]
        public IActionResult Create(VagaViewModel vaga)
        {
            if (ModelState.IsValid)
            {
                if (vaga.DataValidade == null || vaga.DataValidade < DateTime.Now)
                    vaga.DataValidade = DateTime.Now.AddDays(15);

                Vaga.Insert(vaga.Funcao, vaga.Descricao, vaga.DataValidade, vaga.Cidade, decimal.Parse(vaga.Cpf), vaga.NomeResponsavel);
                return Redirect("~/Home");
            }
            return View();
        }
    }
}

GostosinhoEmpregos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link rel="stylesheet" href="~/css/site.css" />

<div class="text-center">
    <h1 class="display-4">Veja nossas vagas:</h1>
</div>

<!--Dei um grau na home, agora mostra os cards bem bonitinhos-->
<!--Ta mostrando só 9 vagas pois eu coloquei um top na query.-->
<div class="container-fluid d-flex flex-wrap">
    @foreach (var vaga in ViewBag.ListaDeVagas)
    {
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@vaga.Funcao - @vaga.Cidade</h5>
                <p class="card-text">@vaga.Descricao</p>
                <p class="card-text"> <small class="text-muted">Publicado dia @vaga.DataCadastro</small></p>
            </div>
            <div class="card-footer">
                <!--Sobre o Url.Action: O primeiro parametro é o metodo, seguido da Controler onde ta o metodo e depois o 
                    parametro do metodo que nesse caso é o idVaga, se tiver mais parametro é so colocar dentro do new-->
                <a href="@Url.Action("VerVaga","Vaga", new {idVaga = vaga.Id })">
                    <button class="btn btn-primary">Detalhes</button>
                </a>   
            </div>
        </div>
    }
</div>

GostosinhoEmpregos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gostosinho Empregos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gostosinho Empregos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vaga" asp-action="Create">Cadastrar vaga</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GostosinhoEmpregos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

GostosinhoEmpregos/Views/Vaga/Create.cshtml
@model VagaViewModel


<form asp-controller="Vaga" asp-action="Create" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="row">
        <label asp-for="Funcao"></label>
        <input type="text" asp-for="Funcao" class="form-control" />
        <span asp-validation-for="Funcao" class="text-danger"></span>
    </div>
    <div class="row">
        <label asp-for="Descricao"></label>
        <textarea class="form-control" asp-for="Descricao"></textarea>
    </div>
    <div class="row mt-2">
        <div class="col">
            <label asp-for="DataValidade"></label>
            <input type="date" asp-for="DataValidade" class="form-control" />
        </div>
        <div class="col">
            <label asp-for="Cidade"></label>
            <input type="text" asp-for="Cidade" class="form-control" />
            <span asp-validation-for="Cidade" class="text-danger"></span>
        </div>
    </div>
    <p>Dados do contratante:</p>
    <div class="row mt-2">
        <div class="col">
            <label asp-for="NomeResponsavel"></label>
            <input type="text" asp-for="NomeResponsavel" class="form-control" />
            <span asp-validation-for="NomeResponsavel" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="Cpf"></label>
            <input type="text" asp-for="Cpf" class="form-control" />
            <span asp-validation-for="Cpf" class="text-danger"></span>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Enviar Vaga</button>
</form>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<!--Aqui temos o script responsavel pela validacao no lado do cliente-->

GostosinhoEmpregos/Views/Vaga/VerVaga.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1 style="text-align:center">Dados da vaga:</h1>

<h5>@ViewBag.Vaga.Funcao</h5>

<p>@ViewBag.Vaga.Descricao</p>

<p>@ViewBag.Vaga.Cidade</p>